### ISSUE TITLE
Comentários no Blog

### ISSUE THREAD

**Issue by woliveiras** [baltazarparra/baltazarparra.github.io#1]
Baltazar, bota um Disqus pra galera ae! 😄

**Comment by baltazarparra** [comment]
@woliveiras eu uso esse blog só pra estudo, mas vou colocar sim, legal o feedback mano, não esperava alguém lendo kkkk.

**Comment by woliveiras** [comment]
UHAUHAUHUHA

Sempre tem mano. :D

**Comment by baltazarparra** [comment]
Habilitado o disqus!
Obrigado pelo incentivo mano will.

**Comment by woliveiras** [comment]
Shoooow! Valeu cara. Ai sim!
